//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Name
    {
        public int Id { get; set; }
        [Display(Name = "Enter the Name")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Name is Required")]
        public string name1 { get; set; }
        [Display(Name = "Enter the PhoneNo")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "PhoneNo is Required")]
        public int phoneno { get; set; }
        [Display(Name = "Enter the age")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "age is Required")]
        public Nullable<int> age { get; set; }
    }
}
